DEBUG:Chroma:Logger created
DEBUG:Chroma:Logger created
DEBUG:Chroma:Logger created
DEBUG:Chroma:Index not found
DEBUG:Chroma:Index saved to .chroma/index/index.bin
DEBUG:Chroma:Index saved to .chroma/index/index.bin
DEBUG:Chroma:time to pre process our knn query: 4.5299530029296875e-06
DEBUG:Chroma:time to run knn query: 0.0001285076141357422
DEBUG:Chroma:time to pre process our knn query: 1.430511474609375e-06
DEBUG:Chroma:time to run knn query: 0.0001316070556640625
DEBUG:Chroma:Logger created
DEBUG:Chroma:Index not found
DEBUG:Chroma:Index saved to .chroma/index/index.bin
DEBUG:Chroma:Index saved to .chroma/index/index.bin
DEBUG:Chroma:Logger created
DEBUG:Chroma:Index not found
DEBUG:Chroma:Index saved to .chroma/index/index.bin
DEBUG:Chroma:Index saved to .chroma/index/index.bin
DEBUG:Chroma:Logger created
DEBUG:Chroma:Index not found
DEBUG:Chroma:Index saved to .chroma/index/index.bin
DEBUG:Chroma:Index saved to .chroma/index/index.bin
DEBUG:Chroma:Logger created
DEBUG:Chroma:Index not found
DEBUG:Chroma:Index saved to .chroma/index/index.bin
DEBUG:Chroma:Index saved to .chroma/index/index.bin
DEBUG:Chroma:Logger created
DEBUG:Chroma:Index not found
DEBUG:Chroma:Index saved to .chroma/index/index.bin
DEBUG:Chroma:Index saved to .chroma/index/index.bin
DEBUG:Chroma:Logger created
DEBUG:Chroma:Index not found
DEBUG:Chroma:Index saved to .chroma/index/index.bin
DEBUG:Chroma:Index saved to .chroma/index/index.bin
INFO:django.utils.autoreload:/media/yaaa3ser/A0CAC126CAC0F994/MATBA5I/django-react-main/backend/api/api/settings/default.py changed, reloading.
DEBUG:Chroma:Logger created
DEBUG:Chroma:Index not found
DEBUG:Chroma:Index saved to .chroma/index/index.bin
DEBUG:Chroma:Index saved to .chroma/index/index.bin
ERROR:django.security.DisallowedHost:Invalid HTTP_HOST header: '127.0.0.1:8000'. You may need to add '127.0.0.1' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/media/yaaa3ser/A0CAC126CAC0F994/MATBA5I/django-react-main/backend/.venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/media/yaaa3ser/A0CAC126CAC0F994/MATBA5I/django-react-main/backend/.venv/lib/python3.10/site-packages/django/utils/deprecation.py", line 135, in __call__
    response = self.process_request(request)
  File "/media/yaaa3ser/A0CAC126CAC0F994/MATBA5I/django-react-main/backend/.venv/lib/python3.10/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/media/yaaa3ser/A0CAC126CAC0F994/MATBA5I/django-react-main/backend/.venv/lib/python3.10/site-packages/django/http/request.py", line 148, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '127.0.0.1:8000'. You may need to add '127.0.0.1' to ALLOWED_HOSTS.
WARNING:django.request:Bad Request: /
INFO:django.utils.autoreload:/media/yaaa3ser/A0CAC126CAC0F994/MATBA5I/django-react-main/backend/api/api/settings/default.py changed, reloading.
DEBUG:Chroma:Logger created
DEBUG:Chroma:Index not found
DEBUG:Chroma:Index saved to .chroma/index/index.bin
DEBUG:Chroma:Index saved to .chroma/index/index.bin
WARNING:django.request:Not Found: /static/admin/css/fonts.css
DEBUG:Chroma:Logger created
DEBUG:Chroma:Index not found
DEBUG:Chroma:Index saved to .chroma/index/index.bin
DEBUG:Chroma:Index saved to .chroma/index/index.bin
DEBUG:Chroma:Logger created
DEBUG:Chroma:Index not found
DEBUG:Chroma:Index saved to .chroma/index/index.bin
DEBUG:Chroma:Index saved to .chroma/index/index.bin
DEBUG:Chroma:Logger created
DEBUG:Chroma:Index not found
DEBUG:Chroma:Index saved to .chroma/index/index.bin
DEBUG:Chroma:Index saved to .chroma/index/index.bin
DEBUG:Chroma:Logger created
DEBUG:Chroma:Index not found
DEBUG:Chroma:Index saved to .chroma/index/index.bin
DEBUG:Chroma:Index saved to .chroma/index/index.bin
ERROR:django.request:Internal Server Error: /whatsapp/
Traceback (most recent call last):
  File "/media/yaaa3ser/A0CAC126CAC0F994/MATBA5I/django-react-main/backend/.venv/lib/python3.10/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/media/yaaa3ser/A0CAC126CAC0F994/MATBA5I/django-react-main/backend/.venv/lib/python3.10/site-packages/rest_framework/views.py", line 167, in http_method_not_allowed
    raise exceptions.MethodNotAllowed(request.method)
rest_framework.exceptions.MethodNotAllowed: Method "GET" not allowed.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/media/yaaa3ser/A0CAC126CAC0F994/MATBA5I/django-react-main/backend/.venv/lib/python3.10/site-packages/rest_framework/settings.py", line 177, in import_from_string
    return import_string(val)
  File "/media/yaaa3ser/A0CAC126CAC0F994/MATBA5I/django-react-main/backend/.venv/lib/python3.10/site-packages/django/utils/module_loading.py", line 30, in import_string
    return cached_import(module_path, class_name)
  File "/media/yaaa3ser/A0CAC126CAC0F994/MATBA5I/django-react-main/backend/.venv/lib/python3.10/site-packages/django/utils/module_loading.py", line 15, in cached_import
    module = import_module(module_path)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'tender'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/media/yaaa3ser/A0CAC126CAC0F994/MATBA5I/django-react-main/backend/.venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/media/yaaa3ser/A0CAC126CAC0F994/MATBA5I/django-react-main/backend/.venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/media/yaaa3ser/A0CAC126CAC0F994/MATBA5I/django-react-main/backend/.venv/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/media/yaaa3ser/A0CAC126CAC0F994/MATBA5I/django-react-main/backend/.venv/lib/python3.10/site-packages/django/views/generic/base.py", line 103, in view
    return self.dispatch(request, *args, **kwargs)
  File "/media/yaaa3ser/A0CAC126CAC0F994/MATBA5I/django-react-main/backend/.venv/lib/python3.10/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/media/yaaa3ser/A0CAC126CAC0F994/MATBA5I/django-react-main/backend/.venv/lib/python3.10/site-packages/rest_framework/views.py", line 463, in handle_exception
    exception_handler = self.get_exception_handler()
  File "/media/yaaa3ser/A0CAC126CAC0F994/MATBA5I/django-react-main/backend/.venv/lib/python3.10/site-packages/rest_framework/views.py", line 298, in get_exception_handler
    return self.settings.EXCEPTION_HANDLER
  File "/media/yaaa3ser/A0CAC126CAC0F994/MATBA5I/django-react-main/backend/.venv/lib/python3.10/site-packages/rest_framework/settings.py", line 225, in __getattr__
    val = perform_import(val, attr)
  File "/media/yaaa3ser/A0CAC126CAC0F994/MATBA5I/django-react-main/backend/.venv/lib/python3.10/site-packages/rest_framework/settings.py", line 166, in perform_import
    return import_from_string(val, setting_name)
  File "/media/yaaa3ser/A0CAC126CAC0F994/MATBA5I/django-react-main/backend/.venv/lib/python3.10/site-packages/rest_framework/settings.py", line 180, in import_from_string
    raise ImportError(msg)
ImportError: Could not import 'tender.utils.drf_exception_handler' for API setting 'EXCEPTION_HANDLER'. ModuleNotFoundError: No module named 'tender'.
DEBUG:Chroma:Logger created
DEBUG:Chroma:Index not found
DEBUG:Chroma:Index saved to .chroma/index/index.bin
DEBUG:Chroma:Index saved to .chroma/index/index.bin
ERROR:django.request:Internal Server Error: /whatsapp/
Traceback (most recent call last):
  File "/media/yaaa3ser/A0CAC126CAC0F994/MATBA5I/django-react-main/backend/.venv/lib/python3.10/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/media/yaaa3ser/A0CAC126CAC0F994/MATBA5I/django-react-main/backend/.venv/lib/python3.10/site-packages/rest_framework/views.py", line 167, in http_method_not_allowed
    raise exceptions.MethodNotAllowed(request.method)
rest_framework.exceptions.MethodNotAllowed: Method "GET" not allowed.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/media/yaaa3ser/A0CAC126CAC0F994/MATBA5I/django-react-main/backend/.venv/lib/python3.10/site-packages/rest_framework/settings.py", line 177, in import_from_string
    return import_string(val)
  File "/media/yaaa3ser/A0CAC126CAC0F994/MATBA5I/django-react-main/backend/.venv/lib/python3.10/site-packages/django/utils/module_loading.py", line 30, in import_string
    return cached_import(module_path, class_name)
  File "/media/yaaa3ser/A0CAC126CAC0F994/MATBA5I/django-react-main/backend/.venv/lib/python3.10/site-packages/django/utils/module_loading.py", line 15, in cached_import
    module = import_module(module_path)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'tender.utils'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/media/yaaa3ser/A0CAC126CAC0F994/MATBA5I/django-react-main/backend/.venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/media/yaaa3ser/A0CAC126CAC0F994/MATBA5I/django-react-main/backend/.venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/media/yaaa3ser/A0CAC126CAC0F994/MATBA5I/django-react-main/backend/.venv/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/media/yaaa3ser/A0CAC126CAC0F994/MATBA5I/django-react-main/backend/.venv/lib/python3.10/site-packages/django/views/generic/base.py", line 103, in view
    return self.dispatch(request, *args, **kwargs)
  File "/media/yaaa3ser/A0CAC126CAC0F994/MATBA5I/django-react-main/backend/.venv/lib/python3.10/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/media/yaaa3ser/A0CAC126CAC0F994/MATBA5I/django-react-main/backend/.venv/lib/python3.10/site-packages/rest_framework/views.py", line 463, in handle_exception
    exception_handler = self.get_exception_handler()
  File "/media/yaaa3ser/A0CAC126CAC0F994/MATBA5I/django-react-main/backend/.venv/lib/python3.10/site-packages/rest_framework/views.py", line 298, in get_exception_handler
    return self.settings.EXCEPTION_HANDLER
  File "/media/yaaa3ser/A0CAC126CAC0F994/MATBA5I/django-react-main/backend/.venv/lib/python3.10/site-packages/rest_framework/settings.py", line 225, in __getattr__
    val = perform_import(val, attr)
  File "/media/yaaa3ser/A0CAC126CAC0F994/MATBA5I/django-react-main/backend/.venv/lib/python3.10/site-packages/rest_framework/settings.py", line 166, in perform_import
    return import_from_string(val, setting_name)
  File "/media/yaaa3ser/A0CAC126CAC0F994/MATBA5I/django-react-main/backend/.venv/lib/python3.10/site-packages/rest_framework/settings.py", line 180, in import_from_string
    raise ImportError(msg)
ImportError: Could not import 'tender.utils.drf_exception_handler' for API setting 'EXCEPTION_HANDLER'. ModuleNotFoundError: No module named 'tender.utils'.
WARNING:django.request:Not Found: /static/admin/css/fonts.css
INFO:django.utils.autoreload:/media/yaaa3ser/A0CAC126CAC0F994/MATBA5I/django-react-main/backend/api/api/urls.py changed, reloading.
DEBUG:Chroma:Logger created
DEBUG:Chroma:Index not found
DEBUG:Chroma:Index saved to .chroma/index/index.bin
DEBUG:Chroma:Index saved to .chroma/index/index.bin
WARNING:django.request:Not Found: /
ERROR:django.request:Internal Server Error: /whatsapp/
Traceback (most recent call last):
  File "/media/yaaa3ser/A0CAC126CAC0F994/MATBA5I/django-react-main/backend/.venv/lib/python3.10/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/media/yaaa3ser/A0CAC126CAC0F994/MATBA5I/django-react-main/backend/.venv/lib/python3.10/site-packages/rest_framework/views.py", line 167, in http_method_not_allowed
    raise exceptions.MethodNotAllowed(request.method)
rest_framework.exceptions.MethodNotAllowed: Method "GET" not allowed.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/media/yaaa3ser/A0CAC126CAC0F994/MATBA5I/django-react-main/backend/.venv/lib/python3.10/site-packages/rest_framework/settings.py", line 177, in import_from_string
    return import_string(val)
  File "/media/yaaa3ser/A0CAC126CAC0F994/MATBA5I/django-react-main/backend/.venv/lib/python3.10/site-packages/django/utils/module_loading.py", line 30, in import_string
    return cached_import(module_path, class_name)
  File "/media/yaaa3ser/A0CAC126CAC0F994/MATBA5I/django-react-main/backend/.venv/lib/python3.10/site-packages/django/utils/module_loading.py", line 15, in cached_import
    module = import_module(module_path)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'tender.utils'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/media/yaaa3ser/A0CAC126CAC0F994/MATBA5I/django-react-main/backend/.venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/media/yaaa3ser/A0CAC126CAC0F994/MATBA5I/django-react-main/backend/.venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/media/yaaa3ser/A0CAC126CAC0F994/MATBA5I/django-react-main/backend/.venv/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/media/yaaa3ser/A0CAC126CAC0F994/MATBA5I/django-react-main/backend/.venv/lib/python3.10/site-packages/django/views/generic/base.py", line 103, in view
    return self.dispatch(request, *args, **kwargs)
  File "/media/yaaa3ser/A0CAC126CAC0F994/MATBA5I/django-react-main/backend/.venv/lib/python3.10/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/media/yaaa3ser/A0CAC126CAC0F994/MATBA5I/django-react-main/backend/.venv/lib/python3.10/site-packages/rest_framework/views.py", line 463, in handle_exception
    exception_handler = self.get_exception_handler()
  File "/media/yaaa3ser/A0CAC126CAC0F994/MATBA5I/django-react-main/backend/.venv/lib/python3.10/site-packages/rest_framework/views.py", line 298, in get_exception_handler
    return self.settings.EXCEPTION_HANDLER
  File "/media/yaaa3ser/A0CAC126CAC0F994/MATBA5I/django-react-main/backend/.venv/lib/python3.10/site-packages/rest_framework/settings.py", line 225, in __getattr__
    val = perform_import(val, attr)
  File "/media/yaaa3ser/A0CAC126CAC0F994/MATBA5I/django-react-main/backend/.venv/lib/python3.10/site-packages/rest_framework/settings.py", line 166, in perform_import
    return import_from_string(val, setting_name)
  File "/media/yaaa3ser/A0CAC126CAC0F994/MATBA5I/django-react-main/backend/.venv/lib/python3.10/site-packages/rest_framework/settings.py", line 180, in import_from_string
    raise ImportError(msg)
ImportError: Could not import 'tender.utils.drf_exception_handler' for API setting 'EXCEPTION_HANDLER'. ModuleNotFoundError: No module named 'tender.utils'.
INFO:django.utils.autoreload:/media/yaaa3ser/A0CAC126CAC0F994/MATBA5I/django-react-main/backend/api/api/urls.py changed, reloading.
DEBUG:Chroma:Logger created
DEBUG:Chroma:Index not found
DEBUG:Chroma:Index saved to .chroma/index/index.bin
DEBUG:Chroma:Index saved to .chroma/index/index.bin
ERROR:django.request:Internal Server Error: /whatsapp/
Traceback (most recent call last):
  File "/media/yaaa3ser/A0CAC126CAC0F994/MATBA5I/django-react-main/backend/.venv/lib/python3.10/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/media/yaaa3ser/A0CAC126CAC0F994/MATBA5I/django-react-main/backend/.venv/lib/python3.10/site-packages/rest_framework/views.py", line 167, in http_method_not_allowed
    raise exceptions.MethodNotAllowed(request.method)
rest_framework.exceptions.MethodNotAllowed: Method "GET" not allowed.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/media/yaaa3ser/A0CAC126CAC0F994/MATBA5I/django-react-main/backend/.venv/lib/python3.10/site-packages/rest_framework/settings.py", line 177, in import_from_string
    return import_string(val)
  File "/media/yaaa3ser/A0CAC126CAC0F994/MATBA5I/django-react-main/backend/.venv/lib/python3.10/site-packages/django/utils/module_loading.py", line 30, in import_string
    return cached_import(module_path, class_name)
  File "/media/yaaa3ser/A0CAC126CAC0F994/MATBA5I/django-react-main/backend/.venv/lib/python3.10/site-packages/django/utils/module_loading.py", line 15, in cached_import
    module = import_module(module_path)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'tender.utils'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/media/yaaa3ser/A0CAC126CAC0F994/MATBA5I/django-react-main/backend/.venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/media/yaaa3ser/A0CAC126CAC0F994/MATBA5I/django-react-main/backend/.venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/media/yaaa3ser/A0CAC126CAC0F994/MATBA5I/django-react-main/backend/.venv/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/media/yaaa3ser/A0CAC126CAC0F994/MATBA5I/django-react-main/backend/.venv/lib/python3.10/site-packages/django/views/generic/base.py", line 103, in view
    return self.dispatch(request, *args, **kwargs)
  File "/media/yaaa3ser/A0CAC126CAC0F994/MATBA5I/django-react-main/backend/.venv/lib/python3.10/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/media/yaaa3ser/A0CAC126CAC0F994/MATBA5I/django-react-main/backend/.venv/lib/python3.10/site-packages/rest_framework/views.py", line 463, in handle_exception
    exception_handler = self.get_exception_handler()
  File "/media/yaaa3ser/A0CAC126CAC0F994/MATBA5I/django-react-main/backend/.venv/lib/python3.10/site-packages/rest_framework/views.py", line 298, in get_exception_handler
    return self.settings.EXCEPTION_HANDLER
  File "/media/yaaa3ser/A0CAC126CAC0F994/MATBA5I/django-react-main/backend/.venv/lib/python3.10/site-packages/rest_framework/settings.py", line 225, in __getattr__
    val = perform_import(val, attr)
  File "/media/yaaa3ser/A0CAC126CAC0F994/MATBA5I/django-react-main/backend/.venv/lib/python3.10/site-packages/rest_framework/settings.py", line 166, in perform_import
    return import_from_string(val, setting_name)
  File "/media/yaaa3ser/A0CAC126CAC0F994/MATBA5I/django-react-main/backend/.venv/lib/python3.10/site-packages/rest_framework/settings.py", line 180, in import_from_string
    raise ImportError(msg)
ImportError: Could not import 'tender.utils.drf_exception_handler' for API setting 'EXCEPTION_HANDLER'. ModuleNotFoundError: No module named 'tender.utils'.
DEBUG:Chroma:Logger created
DEBUG:Chroma:Index not found
DEBUG:Chroma:Index saved to .chroma/index/index.bin
DEBUG:Chroma:Index saved to .chroma/index/index.bin
ERROR:django.request:Internal Server Error: /whatsapp/
Traceback (most recent call last):
  File "/media/yaaa3ser/A0CAC126CAC0F994/MATBA5I/django-react-main/backend/.venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/media/yaaa3ser/A0CAC126CAC0F994/MATBA5I/django-react-main/backend/.venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/media/yaaa3ser/A0CAC126CAC0F994/MATBA5I/django-react-main/backend/.venv/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/media/yaaa3ser/A0CAC126CAC0F994/MATBA5I/django-react-main/backend/.venv/lib/python3.10/site-packages/django/views/generic/base.py", line 103, in view
    return self.dispatch(request, *args, **kwargs)
  File "/media/yaaa3ser/A0CAC126CAC0F994/MATBA5I/django-react-main/backend/.venv/lib/python3.10/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/media/yaaa3ser/A0CAC126CAC0F994/MATBA5I/django-react-main/backend/.venv/lib/python3.10/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/media/yaaa3ser/A0CAC126CAC0F994/MATBA5I/django-react-main/backend/.venv/lib/python3.10/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/media/yaaa3ser/A0CAC126CAC0F994/MATBA5I/django-react-main/backend/.venv/lib/python3.10/site-packages/rest_framework/views.py", line 497, in dispatch
    self.initial(request, *args, **kwargs)
  File "/media/yaaa3ser/A0CAC126CAC0F994/MATBA5I/django-react-main/backend/.venv/lib/python3.10/site-packages/rest_framework/views.py", line 415, in initial
    self.check_permissions(request)
  File "/media/yaaa3ser/A0CAC126CAC0F994/MATBA5I/django-react-main/backend/.venv/lib/python3.10/site-packages/rest_framework/views.py", line 332, in check_permissions
    if not permission.has_permission(request, self):
  File "/media/yaaa3ser/A0CAC126CAC0F994/MATBA5I/django-react-main/backend/.venv/lib/python3.10/site-packages/rest_framework/permissions.py", line 232, in has_permission
    queryset = self._queryset(view)
  File "/media/yaaa3ser/A0CAC126CAC0F994/MATBA5I/django-react-main/backend/.venv/lib/python3.10/site-packages/rest_framework/permissions.py", line 208, in _queryset
    assert hasattr(view, 'get_queryset') \
AssertionError: Cannot apply DjangoModelPermissionsOrAnonReadOnly on a view that does not set `.queryset` or have a `.get_queryset()` method.
INFO:django.utils.autoreload:/media/yaaa3ser/A0CAC126CAC0F994/MATBA5I/django-react-main/backend/api/api/settings/default.py changed, reloading.
DEBUG:Chroma:Logger created
DEBUG:Chroma:Index not found
DEBUG:Chroma:Index saved to .chroma/index/index.bin
DEBUG:Chroma:Index saved to .chroma/index/index.bin
WARNING:django.request:Method Not Allowed: /whatsapp/
WARNING:django.request:Not Found: /
WARNING:django.request:Not Found: /favicon.ico
ERROR:django.request:Internal Server Error: /whatsapp
Traceback (most recent call last):
  File "/media/yaaa3ser/A0CAC126CAC0F994/MATBA5I/django-react-main/backend/.venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/media/yaaa3ser/A0CAC126CAC0F994/MATBA5I/django-react-main/backend/.venv/lib/python3.10/site-packages/django/utils/deprecation.py", line 135, in __call__
    response = self.process_request(request)
  File "/media/yaaa3ser/A0CAC126CAC0F994/MATBA5I/django-react-main/backend/.venv/lib/python3.10/site-packages/django/middleware/common.py", line 54, in process_request
    path = self.get_full_path_with_slash(request)
  File "/media/yaaa3ser/A0CAC126CAC0F994/MATBA5I/django-react-main/backend/.venv/lib/python3.10/site-packages/django/middleware/common.py", line 88, in get_full_path_with_slash
    raise RuntimeError(
RuntimeError: You called this URL via POST, but the URL doesn't end in a slash and you have APPEND_SLASH set. Django can't redirect to the slash URL while maintaining POST data. Change your form to point to 2d39-156-221-111-192.eu.ngrok.io/whatsapp/ (note the trailing slash), or set APPEND_SLASH=False in your Django settings.
ERROR:django.request:Internal Server Error: /whatsapp
Traceback (most recent call last):
  File "/media/yaaa3ser/A0CAC126CAC0F994/MATBA5I/django-react-main/backend/.venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/media/yaaa3ser/A0CAC126CAC0F994/MATBA5I/django-react-main/backend/.venv/lib/python3.10/site-packages/django/utils/deprecation.py", line 135, in __call__
    response = self.process_request(request)
  File "/media/yaaa3ser/A0CAC126CAC0F994/MATBA5I/django-react-main/backend/.venv/lib/python3.10/site-packages/django/middleware/common.py", line 54, in process_request
    path = self.get_full_path_with_slash(request)
  File "/media/yaaa3ser/A0CAC126CAC0F994/MATBA5I/django-react-main/backend/.venv/lib/python3.10/site-packages/django/middleware/common.py", line 88, in get_full_path_with_slash
    raise RuntimeError(
RuntimeError: You called this URL via POST, but the URL doesn't end in a slash and you have APPEND_SLASH set. Django can't redirect to the slash URL while maintaining POST data. Change your form to point to 2d39-156-221-111-192.eu.ngrok.io/whatsapp/ (note the trailing slash), or set APPEND_SLASH=False in your Django settings.
DEBUG:Chroma:time to pre process our knn query: 1.430511474609375e-06
DEBUG:Chroma:time to run knn query: 0.00016045570373535156
DEBUG:Chroma:time to pre process our knn query: 4.291534423828125e-06
DEBUG:Chroma:time to run knn query: 0.00032448768615722656
DEBUG:Chroma:time to pre process our knn query: 4.5299530029296875e-06
DEBUG:Chroma:time to run knn query: 0.0003058910369873047
